"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def get_env(name: str, default=None, required: bool = False):
    value = os.environ.get(name, default)

    if required and not value:
        raise ImproperlyConfigured(f"{name} is required but not configured.")

    return value


def get_bool_env(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)

    if value is None:
        return default

    return value.lower() in ("1", "true", "yes", "on")


def get_list_env(name: str, default: str = "") -> list[str]:
    value = os.environ.get(name, default)

    return [item.strip() for item in value.split(",") if item.strip()]


def get_int_env(name: str, default: int) -> int:
    value = os.environ.get(name)

    if value is None or value == "":
        return default

    try:
        return int(value)
    except ValueError as error:
        raise ImproperlyConfigured(f"{name} must be an integer.") from error


SECRET_KEY = get_env("SECRET_KEY", required=True)
FIELD_ENCRYPTION_KEY = get_env("FIELD_ENCRYPTION_KEY", required=True)
FIELD_HASH_SECRET = get_env("FIELD_HASH_SECRET", required=True)

DEBUG = get_bool_env("DEBUG", default=True)

ALLOWED_HOSTS = get_list_env(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
)

CORS_ALLOWED_ORIGINS = get_list_env(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173",
)

CSRF_TRUSTED_ORIGINS = get_list_env("CSRF_TRUSTED_ORIGINS")

USE_X_FORWARDED_HOST = get_bool_env("USE_X_FORWARDED_HOST", default=False)

if get_bool_env("SECURE_PROXY_SSL_HEADER", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = get_bool_env("SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = get_int_env("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
)
SECURE_HSTS_PRELOAD = get_bool_env("SECURE_HSTS_PRELOAD", default=False)
SESSION_COOKIE_SECURE = get_bool_env("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = get_bool_env("CSRF_COOKIE_SECURE", default=False)
X_FRAME_OPTIONS = get_env("X_FRAME_OPTIONS", default="DENY")
ALLOW_IFRAME_EMBED = get_bool_env("ALLOW_IFRAME_EMBED", default=False)

CORS_ALLOWED_METHODS = [
    "GET",
    "POST",
    "OPTIONS",
]

CORS_ALLOWED_HEADERS = [
    "accept",
    "content-type",
    "authorization",
    "x-requested-with",
]

REPORT_SESSION_CACHE_TTL_SECONDS = int(
    get_env("REPORT_SESSION_CACHE_TTL_SECONDS", default="1800")
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my apps
    "apps.common.apps.CommonConfig",
    "apps.bitrix.apps.BitrixConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.billing.apps.BillingConfig",
    "apps.users.apps.UsersConfig",
]

MIDDLEWARE = [
    "config.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ALLOW_IFRAME_EMBED:
    MIDDLEWARE.remove('django.middleware.clickjacking.XFrameOptionsMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_ENGINE = get_env("DATABASE_ENGINE", default="sqlite").lower()


if DATABASE_ENGINE in ("mysql", "percona"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": get_env("MYSQL_DATABASE", required=True),
            "USER": get_env("MYSQL_USER", required=True),
            "PASSWORD": get_env("MYSQL_PASSWORD", required=True),
            "HOST": get_env("MYSQL_HOST", default="127.0.0.1"),
            "PORT": get_env("MYSQL_PORT", default="3306"),
            "CONN_MAX_AGE": get_int_env("MYSQL_CONN_MAX_AGE", default=60),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": (
                    "SET sql_mode='STRICT_TRANS_TABLES', "
                    "time_zone='+00:00'"
                ),
            },
        }
    }
elif DATABASE_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / get_env("SQLITE_DATABASE_NAME", default="db.sqlite3"),
        }
    }
else:
    raise ImproperlyConfigured(
        "DATABASE_ENGINE must be one of: sqlite, mysql, percona."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = get_env("TIME_ZONE", default="Europe/Moscow")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = get_env("STATIC_URL", default="/static/")
STATIC_ROOT = BASE_DIR / get_env("STATIC_ROOT", default="staticfiles")

MEDIA_URL = get_env("MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / get_env("MEDIA_ROOT", default="media")


CACHE_BACKEND = get_env("CACHE_BACKEND", default="locmem").lower()

if CACHE_BACKEND == "redis":
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": get_env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": False,
            },
            "TIMEOUT": get_int_env("REPORT_SESSION_CACHE_TTL_SECONDS", default=1800),
        }
    }
elif CACHE_BACKEND == "locmem":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "bitrix-report-local-cache",
            "TIMEOUT": get_int_env("REPORT_SESSION_CACHE_TTL_SECONDS", default=1800),
        }
    }
else:
    raise ImproperlyConfigured(
        "CACHE_BACKEND must be one of: locmem, redis."
    )


BITRIX_CLIENT_ID = get_env("BITRIX_CLIENT_ID", default="")
BITRIX_CLIENT_SECRET = get_env("BITRIX_CLIENT_SECRET", default="")
BITRIX_REST_TIMEOUT_SECONDS = get_int_env("BITRIX_REST_TIMEOUT_SECONDS", default=30)
BITRIX_REST_MAX_LIST_PAGES = get_int_env("BITRIX_REST_MAX_LIST_PAGES", default=200)
BITRIX_REST_RETRY_ATTEMPTS = get_int_env("BITRIX_REST_RETRY_ATTEMPTS", default=3)
BITRIX_REST_RETRY_DELAY_SECONDS = float(
    get_env("BITRIX_REST_RETRY_DELAY_SECONDS", default="1")
)
BITRIX_REPORT_SOURCE_LOAD_WORKERS = get_int_env("BITRIX_REPORT_SOURCE_LOAD_WORKERS", default=4)
BITRIX_REPORT_TASK_MONTH_LOAD_WORKERS = get_int_env("BITRIX_REPORT_TASK_MONTH_LOAD_WORKERS", default=3)
REPORT_DATA_PROVIDER = get_env("REPORT_DATA_PROVIDER", default="bitrix").lower()
REPORT_BACKGROUND_BACKEND = get_env("REPORT_BACKGROUND_BACKEND", default="thread").lower()

FRONTEND_URL = get_env("FRONTEND_URL", default="")
BITRIX_FRONTEND_URL = get_env("BITRIX_FRONTEND_URL", default=FRONTEND_URL)

ROBOKASSA_MERCHANT_LOGIN = get_env("ROBOKASSA_MERCHANT_LOGIN", default="")
ROBOKASSA_PASSWORD1 = get_env("ROBOKASSA_PASSWORD1", default="")
ROBOKASSA_PASSWORD2 = get_env("ROBOKASSA_PASSWORD2", default="")
ROBOKASSA_TEST_MODE = get_bool_env("ROBOKASSA_TEST_MODE", default=True)
ROBOKASSA_PAYMENT_URL = get_env(
    "ROBOKASSA_PAYMENT_URL",
    default="https://auth.robokassa.ru/Merchant/Index.aspx",
)

CELERY_BROKER_URL = get_env(
    "CELERY_BROKER_URL",
    default="redis://127.0.0.1:6379/2",
)
CELERY_RESULT_BACKEND = get_env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = get_int_env("CELERY_TASK_TIME_LIMIT", default=1800)
CELERY_TASK_SOFT_TIME_LIMIT = get_int_env("CELERY_TASK_SOFT_TIME_LIMIT", default=1500)
CELERY_WORKER_PREFETCH_MULTIPLIER = get_int_env("CELERY_WORKER_PREFETCH_MULTIPLIER", default=1)

LOG_LEVEL = get_env("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "apps.bitrix": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps.reports": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

SENTRY_DSN = get_env("SENTRY_DSN", default="")

if SENTRY_DSN:
    try:
        import sentry_sdk
    except ImportError as error:
        raise ImproperlyConfigured(
            "SENTRY_DSN is set, but sentry-sdk is not installed."
        ) from error

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=get_env("SENTRY_ENVIRONMENT", default="production" if not DEBUG else "development"),
        traces_sample_rate=float(get_env("SENTRY_TRACES_SAMPLE_RATE", default="0")),
        send_default_pii=False,
    )
