# Generated by Django 6.0.6 on 2026-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('key', models.CharField(max_length=150, unique=True, verbose_name='Ключ')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Системная настройка',
                'verbose_name_plural': 'Системные настройки',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ блокировки')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='Владелец блокировки')),
                ('locked_until', models.DateTimeField(db_index=True, verbose_name='Заблокировано до')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Блокировка задачи',
                'verbose_name_plural': 'Блокировки задач',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_member_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='member_id портала')),
                ('actor_type', models.CharField(choices=[('system', 'Система'), ('bitrix_user', 'Пользователь Битрикс24'), ('admin', 'Администратор'), ('bitrix_event', 'Событие Битрикс24'), ('payment_provider', 'Платежная система')], db_index=True, default='system', max_length=50, verbose_name='Тип инициатора')),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID инициатора')),
                ('action', models.CharField(db_index=True, max_length=150, verbose_name='Действие')),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID сущности')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portal_member_id', 'created_at'], name='common_audi_portal__2602c0_idx'), models.Index(fields=['portal_member_id', 'action'], name='common_audi_portal__c3634b_idx'), models.Index(fields=['entity_type', 'entity_id'], name='common_audi_entity__147a18_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
                ('scope', models.CharField(db_index=True, help_text='Например: bitrix_event, payment_webhook, create_payment', max_length=100, verbose_name='Область')),
                ('portal_member_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='member_id портала')),
                ('request_hash', models.CharField(blank=True, max_length=128, verbose_name='Хэш запроса')),
                ('status', models.CharField(choices=[('started', 'Начато'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='started', max_length=30, verbose_name='Статус')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Заблокировано до')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок действия')),
            ],
            options={
                'verbose_name': 'Ключ идемпотентности',
                'verbose_name_plural': 'Ключи идемпотентности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'status'], name='common_idem_scope_9d5d89_idx'), models.Index(fields=['portal_member_id', 'scope'], name='common_idem_portal__7c402e_idx'), models.Index(fields=['expires_at'], name='common_idem_expires_74f585_idx')],
            },
        ),
    ]
