# Generated by Django 6.0.6 on 2026-08-28 07:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0005_bitrixportal_license_get_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreparedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('prepared_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Подготовлено')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Текущий снимок')),
                ('refresh_interval_minutes', models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name='Интервал обновления')),
                ('settings_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок настроек')),
                ('saved_views_snapshot', models.JSONField(blank=True, default=list, verbose_name='Снимок сохранённых отчётов')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Подготовленные данные')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('payload_size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер данных')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_prepared_snapshots', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_prepared_snapshots', to='bitrix.syncrun', verbose_name='Запуск синхронизации')),
            ],
            options={
                'verbose_name': 'Снимок WEB-дашборда',
                'verbose_name_plural': 'Снимки WEB-дашборда',
                'ordering': ['-prepared_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Плановое'), ('manual', 'Ручное'), ('system', 'Системное')], db_index=True, default='scheduled', max_length=30, verbose_name='Тип запуска')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=30, verbose_name='Статус')),
                ('refresh_interval_minutes', models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name='Интервал обновления')),
                ('requested_by_bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Кем запущено')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено')),
                ('next_planned_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_refresh_runs', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_runs', to='dashboard.dashboardpreparedsnapshot', verbose_name='Успешный снимок')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_refresh_runs', to='bitrix.syncrun', verbose_name='Запуск синхронизации')),
            ],
            options={
                'verbose_name': 'Обновление WEB-дашборда',
                'verbose_name_plural': 'Обновления WEB-дашборда',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('report_id', models.CharField(db_index=True, max_length=150, verbose_name='ID сохранённого отчёта')),
                ('report_name', models.CharField(blank=True, max_length=255, verbose_name='Название отчёта')),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Хэш токена ссылки')),
                ('token_fingerprint', models.CharField(blank=True, max_length=16, verbose_name='Отпечаток токена')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок действия')),
                ('disabled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отключена')),
                ('created_by_bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Кто создал')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_share_links', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Ссылка на WEB-дашборд',
                'verbose_name_plural': 'Ссылки на WEB-дашборд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=100, verbose_name='ID пользователя в Битрикс24')),
                ('user_name', models.CharField(blank=True, max_length=350, verbose_name='Имя пользователя')),
                ('session_key_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Хэш ключа сессии')),
                ('session_key_fingerprint', models.CharField(blank=True, max_length=16, verbose_name='Отпечаток ключа сессии')),
                ('is_trusted_device', models.BooleanField(db_index=True, default=False, verbose_name='Доверенное устройство')),
                ('device_label', models.CharField(blank=True, max_length=255, verbose_name='Название устройства')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Сессия завершена')),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доступ закрыт')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_access_sessions', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_access_sessions', to='bitrix.portaluser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вход в WEB-дашборд',
                'verbose_name_plural': 'Входы в WEB-дашборд',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['portal', 'bitrix_user_id'], name='dashboard_d_portal__e30efe_idx'), models.Index(fields=['portal', 'is_trusted_device'], name='dashboard_d_portal__136458_idx'), models.Index(fields=['portal', 'revoked_at'], name='dashboard_d_portal__265e6c_idx'), models.Index(fields=['last_seen_at'], name='dashboard_d_last_se_e35850_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dashboardpreparedsnapshot',
            index=models.Index(fields=['portal', 'is_current'], name='dashboard_d_portal__22f758_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardpreparedsnapshot',
            index=models.Index(fields=['portal', 'prepared_at'], name='dashboard_d_portal__3567b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardpreparedsnapshot',
            index=models.Index(fields=['portal', 'refresh_interval_minutes'], name='dashboard_d_portal__98ab84_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrefreshrun',
            index=models.Index(fields=['portal', 'status'], name='dashboard_d_portal__4ff4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrefreshrun',
            index=models.Index(fields=['portal', 'trigger_type'], name='dashboard_d_portal__19faa7_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrefreshrun',
            index=models.Index(fields=['portal', 'created_at'], name='dashboard_d_portal__54ad73_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrefreshrun',
            index=models.Index(fields=['portal', 'started_at'], name='dashboard_d_portal__ff945b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsharelink',
            index=models.Index(fields=['portal', 'report_id'], name='dashboard_d_portal__0d7bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsharelink',
            index=models.Index(fields=['portal', 'is_active'], name='dashboard_d_portal__38a4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsharelink',
            index=models.Index(fields=['expires_at'], name='dashboard_d_expires_50d673_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsharelink',
            index=models.Index(fields=['disabled_at'], name='dashboard_d_disable_0a8bbb_idx'),
        ),
    ]
