# Generated by Django 6.0.6

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitrix", "0005_bitrixportal_license_get_fields"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardOwnerLaunchToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="Публичный ID")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Удалено")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Активно")),
                ("bitrix_user_id", models.CharField(db_index=True, max_length=100, verbose_name="ID пользователя в Битрикс24")),
                ("user_name", models.CharField(blank=True, max_length=350, verbose_name="Имя пользователя")),
                ("token_hash", models.CharField(db_index=True, max_length=128, unique=True, verbose_name="Хэш токена запуска")),
                ("token_fingerprint", models.CharField(blank=True, max_length=16, verbose_name="Отпечаток токена")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="Срок действия")),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Использован")),
                ("portal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dashboard_owner_launch_tokens", to="bitrix.bitrixportal", verbose_name="Портал")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboard_owner_launch_tokens", to="bitrix.portaluser", verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Токен запуска WEB-дашборда",
                "verbose_name_plural": "Токены запуска WEB-дашборда",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["portal", "bitrix_user_id"], name="dash_launch_portal_uid_idx"),
                    models.Index(fields=["expires_at"], name="dash_launch_expires_idx"),
                    models.Index(fields=["used_at"], name="dash_launch_used_idx"),
                ],
            },
        ),
    ]
