# Generated by Django 6.0.6 on 2026-06-17 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('code', models.CharField(db_index=True, help_text='Например: free, pro_monthly, pro_yearly, internal_pro.', max_length=100, unique=True, verbose_name='Код тарифа')),
                ('name', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(db_index=True, default='RUB', max_length=10, verbose_name='Валюта')),
                ('billing_period', models.CharField(choices=[('free', 'Бесплатно'), ('month', 'Месяц'), ('year', 'Год')], db_index=True, default='free', max_length=30, verbose_name='Период оплаты')),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, help_text='Для pro_monthly = 1, для pro_yearly = 12. Для free можно оставить пустым.', null=True, verbose_name='Длительность в месяцах')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Например: save_report_data, save_presets, employee_details, export_excel, export_pdf.', verbose_name='Функции тарифа')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Например: max_period_months, max_sources, max_presets.', verbose_name='Лимиты тарифа')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Скрытые тарифы можно использовать для внутреннего Pro-доступа.', verbose_name='Показывать пользователям')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Обычно true только для тарифа free.', verbose_name='Тариф по умолчанию')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order', 'price', 'name'],
                'indexes': [models.Index(fields=['code'], name='billing_pla_code_927eff_idx'), models.Index(fields=['is_active'], name='billing_pla_is_acti_0aba70_idx'), models.Index(fields=['is_public'], name='billing_pla_is_publ_35f18d_idx'), models.Index(fields=['is_default'], name='billing_pla_is_defa_09f517_idx'), models.Index(fields=['billing_period'], name='billing_pla_billing_a2daf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('status', models.CharField(choices=[('free', 'Бесплатная'), ('trial', 'Пробный период'), ('active', 'Активна'), ('past_due', 'Просрочена'), ('canceled', 'Отменена'), ('expired', 'Истекла'), ('blocked', 'Заблокирована')], db_index=True, default='free', max_length=30, verbose_name='Статус')),
                ('provider', models.CharField(choices=[('robokassa', 'Robokassa'), ('manual', 'Ручное включение'), ('none', 'Без провайдера')], db_index=True, default='none', max_length=50, verbose_name='Платежный провайдер')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала')),
                ('paid_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Оплачено до')),
                ('trial_until', models.DateTimeField(blank=True, db_index=True, help_text='Пока можно оставить пустым, если пробный период еще не утвержден.', null=True, verbose_name='Пробный период до')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('is_lifetime', models.BooleanField(db_index=True, default=False, help_text='Используется для ручного Pro-доступа через админку.', verbose_name='Бессрочная подписка')),
                ('auto_renew', models.BooleanField(db_index=True, default=False, verbose_name='Автопродление')),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID подписки у провайдера')),
                ('manual_reason', models.CharField(blank=True, help_text='Например: internal_company, partner, test, manager_access.', max_length=255, verbose_name='Причина ручной выдачи')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Тариф')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('trial', 'Пробный период'), ('internal', 'Внутренний Pro'), ('blocked', 'Заблокирован')], db_index=True, default='free', max_length=30, verbose_name='Уровень доступа')),
                ('has_pro', models.BooleanField(db_index=True, default=False, verbose_name='Есть Pro-доступ')),
                ('is_lifetime', models.BooleanField(db_index=True, default=False, verbose_name='Бессрочный доступ')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доступ действует до')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Доступные функции')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Лимиты')),
                ('source', models.CharField(blank=True, db_index=True, help_text='Например: free, robokassa, manual, trial, internal_company.', max_length=100, verbose_name='Источник доступа')),
                ('last_checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последней проверки')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_records', to='billing.plan', verbose_name='Тариф')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_records', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Доступ портала',
                'verbose_name_plural': 'Доступы порталов',
                'ordering': ['portal'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('order_id', models.CharField(db_index=True, help_text='Наш внутренний ID заказа, по которому потом находим платеж.', max_length=100, unique=True, verbose_name='Внутренний номер заказа')),
                ('provider', models.CharField(choices=[('robokassa', 'Robokassa'), ('manual', 'Ручной платеж')], db_index=True, default='robokassa', max_length=50, verbose_name='Платежный провайдер')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID платежа у провайдера')),
                ('provider_invoice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер счета у провайдера')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Успешно оплачен'), ('canceled', 'Отменен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], db_index=True, default='pending', max_length=50, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(db_index=True, default='RUB', max_length=10, verbose_name='Валюта')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание платежа')),
                ('payment_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на оплату')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата оплаты')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ссылка действует до')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email плательщика')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные провайдера')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan', verbose_name='Тариф')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('provider', models.CharField(choices=[('robokassa', 'Robokassa')], db_index=True, default='robokassa', max_length=50, verbose_name='Платежный провайдер')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Уникальный ключ, чтобы webhook не был обработан повторно.', max_length=255, unique=True, verbose_name='Ключ идемпотентности')),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID события у провайдера')),
                ('event_type', models.CharField(db_index=True, help_text='Например: payment_result, success_redirect, fail_redirect.', max_length=150, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Проигнорировано')], db_index=True, default='received', max_length=30, verbose_name='Статус')),
                ('is_signature_valid', models.BooleanField(db_index=True, default=False, verbose_name='Подпись проверена')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.payment', verbose_name='Платеж')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_webhook_events', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Webhook Robokassa',
                'verbose_name_plural': 'Webhooks Robokassa',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_pay_provide_7c2dc7_idx'), models.Index(fields=['provider', 'event_type'], name='billing_pay_provide_308dcc_idx'), models.Index(fields=['status', 'received_at'], name='billing_pay_status_26d832_idx'), models.Index(fields=['portal', 'received_at'], name='billing_pay_portal__7b7ea4_idx'), models.Index(fields=['is_signature_valid'], name='billing_pay_is_sign_f3140f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['portal', 'status'], name='billing_sub_portal__b73731_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['portal', 'paid_until'], name='billing_sub_portal__fa5a57_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['portal', 'provider'], name='billing_sub_portal__dcdbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'provider_subscription_id'], name='billing_sub_provide_1b17b2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'paid_until'], name='billing_sub_status_f5841f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_lifetime'], name='billing_sub_is_life_1ad86f_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccess',
            index=models.Index(fields=['access_level'], name='billing_por_access__74d324_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccess',
            index=models.Index(fields=['has_pro'], name='billing_por_has_pro_74192e_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccess',
            index=models.Index(fields=['is_lifetime'], name='billing_por_is_life_190d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccess',
            index=models.Index(fields=['valid_until'], name='billing_por_valid_u_3b0b37_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccess',
            index=models.Index(fields=['last_checked_at'], name='billing_por_last_ch_cc3395_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['portal', 'status'], name='billing_pay_portal__2420bc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['portal', 'created_at'], name='billing_pay_portal__8af74c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='billing_pay_provide_f73a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_invoice_id'], name='billing_pay_provide_5f7eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='billing_pay_status_64681e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['expires_at'], name='billing_pay_expires_923650_idx'),
        ),
    ]
