# Generated by Django 6.0.6 on 2026-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Можно вручную указать дату начала trial через админку.', null=True, verbose_name='Пробный период с'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_period',
            field=models.CharField(choices=[('free', 'Бесплатно'), ('month', 'Месяц')], db_index=True, default='free', max_length=30, verbose_name='Период оплаты'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(db_index=True, help_text='Например: free, pro_monthly, internal_pro.', max_length=100, unique=True, verbose_name='Код тарифа'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Для pro_monthly = 1. Для free можно оставить пустым.', null=True, verbose_name='Длительность в месяцах'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Для Free: save_report_state=false, save_report_presets=false, save_report_results=false. Для Pro: save_report_state=true, save_report_presets=true, save_report_results=false.', verbose_name='Функции тарифа'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='internal_pro должен быть скрытым тарифом.', verbose_name='Показывать пользователям'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limits',
            field=models.JSONField(blank=True, default=dict, help_text='Например: max_presets, max_saved_states.', verbose_name='Лимиты тарифа'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена тарифа. Можно менять через админку.', max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='save_report_state/save_report_presets могут быть true, save_report_results всегда false.', verbose_name='Доступные функции'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_lifetime',
            field=models.BooleanField(db_index=True, default=False, help_text='Для внутреннего Manual Pro-доступа через админку.', verbose_name='Бессрочная подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='manual_reason',
            field=models.CharField(blank=True, help_text='Например: internal_company, test, manager_access, trial.', max_length=255, verbose_name='Причина ручной выдачи'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Для месячной Pro-подписки здесь дата окончания доступа.', null=True, verbose_name='Оплачено до'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Можно вручную указать дату окончания trial через админку.', null=True, verbose_name='Пробный период до'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['portal', 'trial_until'], name='billing_sub_portal__9d6775_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'trial_until'], name='billing_sub_status_bb3153_idx'),
        ),
    ]
