# Generated by Django 6.0.6 on 2026-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_trial_started_at_and_more'),
        ('bitrix', '0003_bitrixevent_idempotency_key_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='idempotency_key_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш, чтобы webhook не был обработан повторно.', max_length=64, null=True, unique=True, verbose_name='Хэш ключа идемпотентности'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='signature_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш подписи. Реальная подпись здесь не хранится.', max_length=64, verbose_name='Хэш подписи webhook'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Автоматически очищается от секретов перед сохранением.', verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_provider_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Не сохранять сюда пароли, подписи и другие секреты.', verbose_name='Очищенные исходные данные провайдера'),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Короткий безопасный отпечаток. Реальный ключ здесь не хранится.', max_length=16, verbose_name='Fingerprint ключа идемпотентности'),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Автоматически очищается от секретов перед сохранением.', verbose_name='Очищенные данные события'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Автоматически очищается от секретов перед сохранением.', verbose_name='Дополнительные данные'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['idempotency_key_hash'], name='billing_pay_idempot_75b1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['signature_hash'], name='billing_pay_signatu_a35ae6_idx'),
        ),
    ]
