DEFAULT_REFRESH_INTERVAL_MINUTES = 10
ALLOWED_REFRESH_INTERVAL_MINUTES = (10, 30, 60)
REFRESH_RUN_RETENTION_DAYS = 14
SUCCESSFUL_SNAPSHOT_LIMIT = 3
DASHBOARD_ACCESS_COOKIE_NAME = "sapp_dashboard_access"
DASHBOARD_TRUSTED_DEVICE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365 * 10
