# Generated by Django 6.0.6 on 2026-06-17 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Порядок сортировки')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('code', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Код метрики')),
                ('label', models.CharField(max_length=255, verbose_name='Название метрики')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('value_type', models.CharField(choices=[('number', 'Число'), ('money', 'Деньги'), ('percent', 'Процент'), ('duration', 'Длительность')], db_index=True, default='number', max_length=30, verbose_name='Тип значения')),
                ('calculation_key', models.CharField(db_index=True, help_text='Ключ, по которому backend выбирает функцию расчета метрики.', max_length=150, verbose_name='Ключ расчета')),
                ('source_types', models.JSONField(blank=True, default=list, help_text="Например: ['deal', 'lead', 'invoice'].", verbose_name='Типы источников')),
                ('is_pro', models.BooleanField(db_index=True, default=False, verbose_name='Только для Pro')),
                ('unit', models.CharField(blank=True, help_text='Например: RUB, %, шт.', max_length=50, verbose_name='Единица измерения')),
                ('default_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки по умолчанию')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['section__sort_order', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MetricSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Порядок сортировки')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код раздела')),
                ('label', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел метрик',
                'verbose_name_plural': 'Разделы метрик',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CrmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('external_key', models.CharField(db_index=True, help_text='Например: lead-default, deal-0, smart-180-0, invoice-default.', max_length=150, verbose_name='Внешний ключ источника')),
                ('source_type', models.CharField(choices=[('lead', 'Лиды'), ('deal', 'Сделки'), ('smart_process', 'Смарт-процесс'), ('invoice', 'Счета'), ('task', 'Задачи'), ('call', 'Звонки'), ('other', 'Другое')], db_index=True, max_length=50, verbose_name='Тип источника')),
                ('entity_type_id', models.IntegerField(blank=True, db_index=True, help_text='Используется для смарт-процессов и CRM-сущностей Битрикс24.', null=True, verbose_name='Entity Type ID')),
                ('category_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID категории / воронки')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('source_label', models.CharField(blank=True, max_length=255, verbose_name='Отображаемое название')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Доступен в Битрикс24')),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата последней синхронизации')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные источника')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_sources', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Источник CRM',
                'verbose_name_plural': 'Источники CRM',
                'ordering': ['source_type', 'category_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы'), ('quarters', 'Кварталы'), ('years', 'Годы')], db_index=True, max_length=30, verbose_name='Тип периода')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='Конец периода')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=100, verbose_name='ID сотрудника в Битрикс24')),
                ('user_name', models.CharField(blank=True, max_length=350, verbose_name='Имя сотрудника')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Аватар')),
                ('metric_value', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='Значение метрики')),
                ('currency', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Валюта')),
                ('calculated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата расчета')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_metrics', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_metrics', to='reports.crmsource', verbose_name='Источник')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_metrics', to='bitrix.syncrun', verbose_name='Синхронизация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_metrics', to='bitrix.portaluser', verbose_name='Сотрудник')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_metrics', to='reports.metric', verbose_name='Метрика')),
            ],
            options={
                'verbose_name': 'Метрика сотрудника',
                'verbose_name_plural': 'Метрики сотрудников',
                'ordering': ['portal', 'source', 'metric', 'period_start', 'user_name'],
            },
        ),
        migrations.CreateModel(
            name='MetricDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы'), ('quarters', 'Кварталы'), ('years', 'Годы')], db_index=True, max_length=30, verbose_name='Тип периода')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='Конец периода')),
                ('entity_type', models.CharField(choices=[('lead', 'Лид'), ('deal', 'Сделка'), ('smart_process', 'Смарт-процесс'), ('invoice', 'Счет'), ('task', 'Задача'), ('call', 'Звонок'), ('other', 'Другое')], db_index=True, max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(db_index=True, max_length=100, verbose_name='ID сущности в Битрикс24')),
                ('entity_title', models.CharField(blank=True, max_length=500, verbose_name='Название сущности')),
                ('entity_url', models.URLField(blank=True, max_length=700, verbose_name='Ссылка на сущность в Битрикс24')),
                ('responsible_bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID ответственного в Битрикс24')),
                ('responsible_name', models.CharField(blank=True, max_length=350, verbose_name='Имя ответственного')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Валюта')),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Статус')),
                ('stage_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Стадия')),
                ('category_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Категория / воронка')),
                ('created_at_bitrix', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата создания в Битрикс24')),
                ('closed_at_bitrix', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата закрытия в Битрикс24')),
                ('updated_at_bitrix', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата обновления в Битрикс24')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные сущности')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='reports.metric', verbose_name='Метрика')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_details', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_details', to='bitrix.portaluser', verbose_name='Ответственный')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_details', to='reports.crmsource', verbose_name='Источник')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_details', to='bitrix.syncrun', verbose_name='Синхронизация')),
            ],
            options={
                'verbose_name': 'Детализация метрики',
                'verbose_name_plural': 'Детализация метрик',
                'ordering': ['-period_start', 'entity_type', 'entity_id'],
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='reports.metricsection', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='ReportBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('requested_by_bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID пользователя Битрикс24')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы'), ('quarters', 'Кварталы'), ('years', 'Годы')], db_index=True, max_length=30, verbose_name='Тип периода')),
                ('date_from', models.DateTimeField(db_index=True, verbose_name='Дата с')),
                ('date_to', models.DateTimeField(db_index=True, verbose_name='Дата по')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Источники')),
                ('metrics', models.JSONField(blank=True, default=list, verbose_name='Метрики')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Опции отчета')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=30, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID фоновой задачи')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_builds', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_builds', to='bitrix.portaluser', verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Построение отчета',
                'verbose_name_plural': 'Построения отчетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы'), ('quarters', 'Кварталы'), ('years', 'Годы')], db_index=True, max_length=30, verbose_name='Тип периода')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='Конец периода')),
                ('metric_value', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='Значение метрики')),
                ('currency', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Валюта')),
                ('calculated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата расчета')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_data', to='reports.metric', verbose_name='Метрика')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_data', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_data', to='reports.crmsource', verbose_name='Источник')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_data', to='bitrix.syncrun', verbose_name='Синхронизация')),
            ],
            options={
                'verbose_name': 'Данные отчета',
                'verbose_name_plural': 'Данные отчетов',
                'ordering': ['portal', 'source', 'metric', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='ReportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Источники, метрики, период, вид графика, таблица, пороги и другие настройки.', verbose_name='Настройки отчета')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Отчет по умолчанию')),
                ('created_by_bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID создателя в Битрикс24')),
                ('created_by_name', models.CharField(blank=True, max_length=350, verbose_name='Имя создателя')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_presets', to='bitrix.portaluser', verbose_name='Создал')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_presets', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Сохраненный отчет',
                'verbose_name_plural': 'Сохраненные отчеты',
                'ordering': ['portal', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='crmsource',
            index=models.Index(fields=['portal', 'source_type'], name='reports_crm_portal__f939af_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsource',
            index=models.Index(fields=['portal', 'is_active'], name='reports_crm_portal__5bca9c_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsource',
            index=models.Index(fields=['portal', 'is_available'], name='reports_crm_portal__4326c7_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsource',
            index=models.Index(fields=['portal', 'entity_type_id', 'category_id'], name='reports_crm_portal__355211_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmsource',
            constraint=models.UniqueConstraint(fields=('portal', 'external_key'), name='unique_crm_source_external_key'),
        ),
        migrations.AddIndex(
            model_name='employeemetric',
            index=models.Index(fields=['portal', 'bitrix_user_id'], name='reports_emp_portal__f7d073_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemetric',
            index=models.Index(fields=['portal', 'user_name'], name='reports_emp_portal__588c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemetric',
            index=models.Index(fields=['portal', 'metric', 'period_start'], name='reports_emp_portal__355580_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemetric',
            index=models.Index(fields=['portal', 'source', 'metric'], name='reports_emp_portal__6d0da6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemetric',
            index=models.Index(fields=['period_start', 'period_end'], name='reports_emp_period__bf5e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeemetric',
            constraint=models.UniqueConstraint(fields=('portal', 'source', 'metric', 'period_key', 'period_start', 'period_end', 'bitrix_user_id'), name='unique_employee_metric_period_value'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['portal', 'source', 'metric'], name='reports_met_portal__a69da1_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['portal', 'period_key', 'period_start'], name='reports_met_portal__5107b7_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['portal', 'entity_type', 'entity_id'], name='reports_met_portal__b176f0_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['portal', 'responsible_bitrix_user_id'], name='reports_met_portal__318e38_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['portal', 'status'], name='reports_met_portal__943afc_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['created_at_bitrix'], name='reports_met_created_c14570_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdetail',
            index=models.Index(fields=['closed_at_bitrix'], name='reports_met_closed__21caac_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricdetail',
            constraint=models.UniqueConstraint(fields=('portal', 'source', 'metric', 'period_key', 'period_start', 'period_end', 'entity_type', 'entity_id'), name='unique_metric_detail_entity'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['section', 'sort_order'], name='reports_met_section_f797fb_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['value_type'], name='reports_met_value_t_e7abd1_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['is_active', 'is_pro'], name='reports_met_is_acti_537bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['calculation_key'], name='reports_met_calcula_001082_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['portal', 'status'], name='reports_rep_portal__f638fa_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['portal', 'created_at'], name='reports_rep_portal__4effe9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['period_key', 'date_from', 'date_to'], name='reports_rep_period__7a28f1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['celery_task_id'], name='reports_rep_celery__60ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdata',
            index=models.Index(fields=['portal', 'period_key', 'period_start', 'period_end'], name='reports_rep_portal__764fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdata',
            index=models.Index(fields=['portal', 'source', 'metric'], name='reports_rep_portal__2b2535_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdata',
            index=models.Index(fields=['portal', 'metric', 'period_start'], name='reports_rep_portal__4cdb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdata',
            index=models.Index(fields=['source', 'period_start'], name='reports_rep_source__f92e53_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdata',
            index=models.Index(fields=['calculated_at'], name='reports_rep_calcula_28257c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdata',
            constraint=models.UniqueConstraint(fields=('portal', 'source', 'metric', 'period_key', 'period_start', 'period_end'), name='unique_report_data_period_value'),
        ),
        migrations.AddIndex(
            model_name='reportpreset',
            index=models.Index(fields=['portal', 'is_active'], name='reports_rep_portal__ade46d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportpreset',
            index=models.Index(fields=['portal', 'is_default'], name='reports_rep_portal__91a7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportpreset',
            index=models.Index(fields=['portal', 'created_by_bitrix_user_id'], name='reports_rep_portal__f8193d_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportpreset',
            constraint=models.UniqueConstraint(fields=('portal', 'name'), name='unique_report_preset_name_per_portal'),
        ),
    ]
