# Generated by Django 6.0.6 on 2026-06-18 08:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ сессии')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=100, verbose_name='ID пользователя в Битрикс24')),
                ('user_name', models.CharField(blank=True, max_length=350, verbose_name='Имя пользователя')),
                ('status', models.CharField(choices=[('opened', 'Открыта'), ('active', 'Активна'), ('idle', 'Без активности'), ('closed', 'Закрыта'), ('expired', 'Истекла'), ('error', 'Ошибка')], db_index=True, default='opened', max_length=30, verbose_name='Статус')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], db_index=True, default='months', max_length=30, verbose_name='Тип периода')),
                ('state_snapshot', models.JSONField(blank=True, default=dict, help_text='Текущие фильтры и настройки сессии на момент расчета.', verbose_name='Снимок настроек')),
                ('filters_hash', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Хэш фильтров')),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Ключ временных результатов в cache / Redis')),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=7200, help_text='По умолчанию 2 часа.', verbose_name='TTL кеша в секундах')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата открытия')),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('last_calculated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последний расчет')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата закрытия')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата истечения')),
                ('result_size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер временного результата')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Сессия отчета',
                'verbose_name_plural': 'Сессии отчетов',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=100, verbose_name='ID пользователя в Битрикс24')),
                ('user_name', models.CharField(blank=True, max_length=350, verbose_name='Имя пользователя')),
                ('state_type', models.CharField(choices=[('last_used', 'Последнее состояние'), ('custom', 'Пользовательское состояние')], db_index=True, default='last_used', max_length=30, verbose_name='Тип состояния')),
                ('state_key', models.CharField(db_index=True, default='default', help_text='Например: default, sales_report, manager_report.', max_length=100, verbose_name='Ключ состояния')),
                ('period_key', models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], db_index=True, default='months', max_length=30, verbose_name='Тип периода')),
                ('state', models.JSONField(blank=True, default=dict, help_text='Фильтры, выбранные метрики, источники, вид графика, настройки таблицы.', verbose_name='Состояние отчета')),
                ('filters_hash', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Хэш фильтров')),
                ('last_saved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего сохранения')),
            ],
            options={
                'verbose_name': 'Состояние отчета',
                'verbose_name_plural': 'Состояния отчетов',
                'ordering': ['portal', 'bitrix_user_id', 'state_key'],
            },
        ),
        migrations.RemoveIndex(
            model_name='employeemetric',
            name='reports_emp_portal__f7d073_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeemetric',
            name='reports_emp_portal__588c8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeemetric',
            name='reports_emp_portal__355580_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeemetric',
            name='reports_emp_portal__6d0da6_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeemetric',
            name='reports_emp_period__bf5e09_idx',
        ),
        migrations.RemoveConstraint(
            model_name='employeemetric',
            name='unique_employee_metric_period_value',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_portal__a69da1_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_portal__5107b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_portal__b176f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_portal__318e38_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_portal__943afc_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_created_c14570_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricdetail',
            name='reports_met_closed__21caac_idx',
        ),
        migrations.RemoveConstraint(
            model_name='metricdetail',
            name='unique_metric_detail_entity',
        ),
        migrations.RemoveIndex(
            model_name='reportdata',
            name='reports_rep_portal__764fd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdata',
            name='reports_rep_portal__2b2535_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdata',
            name='reports_rep_portal__4cdb3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdata',
            name='reports_rep_source__f92e53_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdata',
            name='reports_rep_calcula_28257c_idx',
        ),
        migrations.RemoveConstraint(
            model_name='reportdata',
            name='unique_report_data_period_value',
        ),
        migrations.RemoveField(
            model_name='reportbuild',
            name='result_payload',
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Ключ результата в cache / Redis'),
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='filters_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Хэш фильтров'),
        ),
        migrations.AlterField(
            model_name='crmsource',
            name='source_type',
            field=models.CharField(choices=[('lead', 'Лиды'), ('deal', 'Сделки'), ('smart_process', 'Смарт-процесс'), ('invoice', 'Счета'), ('task', 'Задачи'), ('call', 'Звонки'), ('activity', 'Дела'), ('email', 'Письма'), ('message', 'Сообщения'), ('company', 'Компании'), ('contact', 'Контакты'), ('other', 'Другое')], db_index=True, max_length=50, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='code',
            field=models.CharField(db_index=True, help_text='Например: deals_created, deals_won_sum, invoices_paid_sum.', max_length=150, unique=True, verbose_name='Код метрики'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='date_from',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата с'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='date_to',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата по'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='period_key',
            field=models.CharField(choices=[('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], db_index=True, default='months', max_length=30, verbose_name='Тип периода'),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('canceled', 'Отменено'), ('expired', 'Истекло')], db_index=True, default='pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reportpreset',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Источники, метрики, период, вид графика, таблица, фильтры и другие настройки.', verbose_name='Настройки отчета'),
        ),
        migrations.AddField(
            model_name='reportsession',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sessions', to='bitrix.bitrixportal', verbose_name='Портал'),
        ),
        migrations.AddField(
            model_name='reportsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sessions', to='bitrix.portaluser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='reports.reportsession', verbose_name='Сессия отчета'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['cache_key'], name='reports_rep_cache_k_39dab1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuild',
            index=models.Index(fields=['filters_hash'], name='reports_rep_filters_c697e1_idx'),
        ),
        migrations.AddField(
            model_name='reportstate',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_states', to='bitrix.bitrixportal', verbose_name='Портал'),
        ),
        migrations.AddField(
            model_name='reportstate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_states', to='bitrix.portaluser', verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='employeemetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='employeemetric',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='employeemetric',
            name='source',
        ),
        migrations.RemoveField(
            model_name='employeemetric',
            name='sync_run',
        ),
        migrations.RemoveField(
            model_name='employeemetric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metricdetail',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricdetail',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='metricdetail',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='metricdetail',
            name='source',
        ),
        migrations.RemoveField(
            model_name='metricdetail',
            name='sync_run',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='sync_run',
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['portal', 'bitrix_user_id'], name='reports_rep_portal__a1ed10_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['portal', 'status'], name='reports_rep_portal__597dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['status', 'expires_at'], name='reports_rep_status_9a4ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['last_activity_at'], name='reports_rep_last_ac_797a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['cache_key'], name='reports_rep_cache_k_4c4c29_idx'),
        ),
        migrations.AddIndex(
            model_name='reportstate',
            index=models.Index(fields=['portal', 'bitrix_user_id'], name='reports_rep_portal__88070e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportstate',
            index=models.Index(fields=['portal', 'state_type'], name='reports_rep_portal__6d1d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportstate',
            index=models.Index(fields=['portal', 'period_key'], name='reports_rep_portal__86284f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportstate',
            index=models.Index(fields=['last_saved_at'], name='reports_rep_last_sa_865718_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportstate',
            constraint=models.UniqueConstraint(fields=('portal', 'bitrix_user_id', 'state_type', 'state_key'), name='unique_report_state_per_user'),
        ),
        migrations.DeleteModel(
            name='EmployeeMetric',
        ),
        migrations.DeleteModel(
            name='MetricDetail',
        ),
        migrations.DeleteModel(
            name='ReportData',
        ),
    ]
