# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_reportsession_reportstate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsession",
            name="cache_ttl_seconds",
            field=models.PositiveIntegerField(
                default=1800,
                help_text="По умолчанию 30 минут.",
                verbose_name="TTL кеша в секундах",
            ),
        ),
    ]
