# Generated by Django 6.0.6 on 2026-07-08 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0005_bitrixportal_license_get_fields'),
        ('reports', '0003_alter_reportsession_cache_ttl_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Полный слепок настроек интерфейса: фильтры, метрики, порядок, пороги, график, расписание, настройки приложения.', verbose_name='Настройки отчета')),
                ('saved_views', models.JSONField(blank=True, default=list, help_text='Список пользовательских пресетов (SavedReportViewOption) для портала.', verbose_name='Сохранённые представления')),
                ('app_settings', models.JSONField(blank=True, default=dict, help_text='AppSettings: reportBuilderUserIds, moneyViewerUserIds, viewSaverUserIds.', verbose_name='Настройки приложения')),
                ('detail_column_widths', models.JSONField(blank=True, default=dict, help_text='Сохранённые ширины колонок в модалке детализации.', verbose_name='Ширины колонок детализации')),
                ('last_saved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего сохранения')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Настройки отчета портала',
                'verbose_name_plural': 'Настройки отчетов порталов',
                'ordering': ['portal'],
            },
        ),
    ]
