# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0005_bitrixportal_license_get_fields'),
        ('reports', '0004_portal_report_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCrmRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source_id', models.CharField(db_index=True, max_length=150, verbose_name='ID источника')),
                ('entity_id', models.CharField(max_length=64, verbose_name='ID сущности')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Дата события')),
                ('payload', models.JSONField(default=dict, verbose_name='Строка CRM')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_warehouse_rows', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Строка CRM склада',
                'verbose_name_plural': 'Строки CRM склада',
            },
        ),
        migrations.CreateModel(
            name='PortalCrmSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Идёт загрузка'), ('ready', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='idle', max_length=20, verbose_name='Статус')),
                ('coverage_from', models.DateTimeField(blank=True, null=True, verbose_name='Покрытие с')),
                ('coverage_to', models.DateTimeField(blank=True, null=True, verbose_name='Покрытие по')),
                ('next_chunk_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец следующего куска')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('progress_message', models.CharField(blank=True, max_length=255, verbose_name='Сообщение прогресса')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('last_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало текущего шага')),
                ('last_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец последнего шага')),
                ('last_incremental_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний инкремент')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_sync_state', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Состояние склада CRM',
                'verbose_name_plural': 'Состояния склада CRM',
            },
        ),
        migrations.AddIndex(
            model_name='portalcrmrow',
            index=models.Index(fields=['portal', 'source_id', 'occurred_at'], name='reports_por_portal__crmrow_idx'),
        ),
        migrations.AddIndex(
            model_name='portalcrmrow',
            index=models.Index(fields=['portal', 'occurred_at'], name='reports_por_portal__crmocc_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalcrmrow',
            constraint=models.UniqueConstraint(fields=('portal', 'source_id', 'entity_id'), name='reports_portalcrmrow_portal_source_entity_uniq'),
        ),
    ]
