# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_portal_crm_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcrmsyncstate',
            name='source_coverage',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Диапазоны дат, которые уже сохранили из построенных PRO-отчётов, по source_id.',
                verbose_name='Покрытие по источникам',
            ),
        ),
    ]
