# Generated by Django 6.0.6 on 2026-06-17 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('member_id', models.CharField(db_index=True, help_text='Уникальный идентификатор портала Битрикс24.', max_length=100, unique=True, verbose_name='member_id портала')),
                ('domain', models.CharField(db_index=True, help_text='Например: company.bitrix24.ru', max_length=255, verbose_name='Домен портала')),
                ('protocol', models.CharField(default='https', max_length=20, verbose_name='Протокол')),
                ('client_endpoint', models.URLField(blank=True, max_length=500, verbose_name='Client endpoint')),
                ('server_endpoint', models.URLField(blank=True, max_length=500, verbose_name='Server endpoint')),
                ('status', models.CharField(choices=[('installing', 'Устанавливается'), ('installed', 'Установлено'), ('active', 'Активно'), ('uninstalled', 'Удалено'), ('blocked', 'Заблокировано'), ('error', 'Ошибка')], db_index=True, default='installing', max_length=30, verbose_name='Статус установки')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата установки')),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления приложения')),
                ('last_opened_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее открытие приложения')),
                ('installed_by_user_id', models.CharField(blank=True, max_length=100, verbose_name='ID пользователя, установившего приложение')),
                ('installed_by_user_name', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя, установившего приложение')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Язык портала')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Часовой пояс портала')),
                ('application_token_encrypted', models.TextField(blank=True, help_text='Хранить только в зашифрованном виде.', verbose_name='Application token')),
                ('raw_install_payload', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные установки')),
            ],
            options={
                'verbose_name': 'Портал Битрикс24',
                'verbose_name_plural': 'Порталы Битрикс24',
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['member_id'], name='bitrix_bitr_member__500f3a_idx'), models.Index(fields=['domain'], name='bitrix_bitr_domain_bb88a8_idx'), models.Index(fields=['status'], name='bitrix_bitr_status_647461_idx'), models.Index(fields=['is_active'], name='bitrix_bitr_is_acti_67ef9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('sync_type', models.CharField(choices=[('initial', 'Первичная синхронизация'), ('manual', 'Ручная синхронизация'), ('scheduled', 'Плановая синхронизация'), ('webhook', 'Синхронизация по событию'), ('period_recalc', 'Пересчет периода'), ('users', 'Синхронизация сотрудников'), ('crm_sources', 'Синхронизация источников CRM'), ('report_data', 'Расчет отчетных данных')], db_index=True, max_length=50, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично выполнено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=30, verbose_name='Статус')),
                ('date_from', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Период с')),
                ('date_to', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Период по')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID фоновой задачи')),
                ('triggered_by_user_id', models.CharField(blank=True, max_length=100, verbose_name='Кем запущено')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации',
                'verbose_name_plural': 'Запуски синхронизаций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitrixEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('event_name', models.CharField(db_index=True, max_length=150, verbose_name='Название события')),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID сущности')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ключ идемпотентности')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Проигнорировано')], db_index=True, default='received', max_length=30, verbose_name='Статус')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка обработки')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bitrix.bitrixportal', verbose_name='Портал')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bitrix.syncrun', verbose_name='Связанная синхронизация')),
            ],
            options={
                'verbose_name': 'Событие Битрикс24',
                'verbose_name_plural': 'События Битрикс24',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='BitrixAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('access_token_encrypted', models.TextField(help_text='Хранить только в зашифрованном виде.', verbose_name='Access token')),
                ('refresh_token_encrypted', models.TextField(help_text='Хранить только в зашифрованном виде.', verbose_name='Refresh token')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Access token действует до')),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления токена')),
                ('scope', models.TextField(blank=True, verbose_name='Права доступа')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Тип токена')),
                ('auth_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID пользователя авторизации')),
                ('auth_user_name', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя авторизации')),
                ('raw_auth_payload', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные авторизации')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'OAuth-токен Битрикс24',
                'verbose_name_plural': 'OAuth-токены Битрикс24',
                'indexes': [models.Index(fields=['expires_at'], name='bitrix_bitr_expires_7d76d7_idx'), models.Index(fields=['auth_user_id'], name='bitrix_bitr_auth_us_3a85d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=100, verbose_name='ID пользователя в Битрикс24')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=350, verbose_name='Полное имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Аватар')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('department_ids', models.JSONField(blank=True, default=list, verbose_name='ID отделов')),
                ('department_names', models.JSONField(blank=True, default=list, verbose_name='Названия отделов')),
                ('is_admin', models.BooleanField(db_index=True, default=False, verbose_name='Администратор портала')),
                ('is_extranet', models.BooleanField(db_index=True, default=False, verbose_name='Экстранет-пользователь')),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата последней синхронизации')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные пользователя')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Сотрудник портала',
                'verbose_name_plural': 'Сотрудники портала',
                'ordering': ['full_name', 'bitrix_user_id'],
                'indexes': [models.Index(fields=['portal', 'bitrix_user_id'], name='bitrix_port_portal__17bd1f_idx'), models.Index(fields=['portal', 'is_active'], name='bitrix_port_portal__ee1ae7_idx'), models.Index(fields=['portal', 'full_name'], name='bitrix_port_portal__4ecb1c_idx'), models.Index(fields=['last_synced_at'], name='bitrix_port_last_sy_28c8dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('portal', 'bitrix_user_id'), name='unique_portal_bitrix_user')],
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['portal', 'sync_type'], name='bitrix_sync_portal__2fd304_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['portal', 'status'], name='bitrix_sync_portal__a8f988_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['portal', 'created_at'], name='bitrix_sync_portal__0d912d_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['date_from', 'date_to'], name='bitrix_sync_date_fr_6a96c7_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['celery_task_id'], name='bitrix_sync_celery__5e0208_idx'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['portal', 'event_name'], name='bitrix_bitr_portal__8c78f6_idx'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['portal', 'status'], name='bitrix_bitr_portal__5d84d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['portal', 'received_at'], name='bitrix_bitr_portal__c08d79_idx'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='bitrix_bitr_entity__dc9d73_idx'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['status', 'received_at'], name='bitrix_bitr_status_6a63e7_idx'),
        ),
    ]
