# Generated by Django 6.0.6 on 2026-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixauthtoken',
            name='access_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш access_token для сравнения и отладки.', max_length=64, verbose_name='Хэш access token'),
        ),
        migrations.AddField(
            model_name='bitrixauthtoken',
            name='refresh_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш refresh_token для сравнения и отладки.', max_length=64, verbose_name='Хэш refresh token'),
        ),
        migrations.AddField(
            model_name='bitrixportal',
            name='application_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш application_token для сравнения и отладки.', max_length=64, verbose_name='Хэш application token'),
        ),
        migrations.AlterField(
            model_name='bitrixauthtoken',
            name='access_token_encrypted',
            field=models.TextField(blank=True, default='', help_text='Зашифрованный access_token. Не показывать в админке.', verbose_name='Access token, encrypted'),
        ),
        migrations.AlterField(
            model_name='bitrixauthtoken',
            name='raw_auth_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Не сохранять сюда AUTH_ID, REFRESH_ID, access_token, refresh_token и другие секреты.', verbose_name='Очищенные исходные данные авторизации'),
        ),
        migrations.AlterField(
            model_name='bitrixauthtoken',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default='', help_text='Зашифрованный refresh_token. Не показывать в админке.', verbose_name='Refresh token, encrypted'),
        ),
        migrations.AlterField(
            model_name='bitrixportal',
            name='application_token_encrypted',
            field=models.TextField(blank=True, help_text='Зашифрованный application_token. Не показывать в админке.', verbose_name='Application token, encrypted'),
        ),
        migrations.AlterField(
            model_name='bitrixportal',
            name='protocol',
            field=models.CharField(choices=[('https', 'HTTPS'), ('http', 'HTTP')], default='https', max_length=20, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='bitrixportal',
            name='raw_install_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Не сохранять сюда AUTH_ID, REFRESH_ID, application_token и другие секреты.', verbose_name='Очищенные исходные данные установки'),
        ),
    ]
