# Generated by Django 6.0.6 on 2026-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0002_bitrixauthtoken_access_token_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixevent',
            name='idempotency_key_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Необратимый хэш для защиты от повторной обработки события.', max_length=64, null=True, unique=True, verbose_name='Хэш ключа идемпотентности'),
        ),
        migrations.AlterField(
            model_name='bitrixevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Короткий безопасный отпечаток. Реальный ключ здесь не хранится.', max_length=16, verbose_name='Fingerprint ключа идемпотентности'),
        ),
        migrations.AddIndex(
            model_name='bitrixevent',
            index=models.Index(fields=['idempotency_key_hash'], name='bitrix_bitr_idempot_f540bb_idx'),
        ),
    ]
